
dataGap = {
    "LineKey" : "v_100",
    "RecKey" : "v_100",
    "DateModified" : "date",
    "FormType" : "text",
    "FormDate" : "date",
    "Direction" : "text",
    "Measure" : "float",
    "LineLengthAmount" : "float",
    "GapMin" : "float",
    "GapData" : "float",
    "PerennialsCanopy" : "float",
    "AnnualGrassesCanopy" : "float",
    "AnnualForbsCanopy" : "float",
    "OtherCanopy" : "float",
    "Notes" : "text",
    "NoCanopyGaps" : "float",
    "NoBasalGaps" : "float",
    "DateLoadedInDb" : "date",
    "PerennialsBasal" : "float",
    "AnnualGrassesBasal" : "float",
    "AnnualForbsBasal" : "float",
    "OtherBasal" : "float",
    "PrimaryKey" : "v_100",
    "DBKey" : "text",
    "SeqNo" : "text",
    "RecType" : "text",
    "GapStart" : "float",
    "GapEnd" : "float",
    "Gap" : "float",
    "ProjectKey" : "text",

}
