
dataSpeciesInventory = {
    "LineKey" : "v_100",
    "RecKey" : "v_100",
    "DateModified" : "date",
    "FormType" : "text",
    "FormDate" : "date",


    "SpecRichMethod" : "float",
    "SpecRichMeasure" : "float",
    "SpecRichNbrSubPlots" : "float",
    "SpecRich1Container" : "float",
    "SpecRich1Shape" : "float",
    "SpecRich1Dim1" : "float",
    "SpecRich1Dim2" : "float",
    "SpecRich1Area" : "float",
    "SpecRich2Container":"float",
    "SpecRich2Shape" : "float",
    "SpecRich2Dim1":"float",
    "SpecRich2Dim2":"float",
    "SpecRich2Area" :"float",
    "SpecRich3Container" : "float",
    "SpecRich3Shape" :"float",
    "SpecRich3Dim1":"float",
    "SpecRich3Dim2":"float",
    "SpecRich3Area":"float",
    "SpecRich4Container":"float",
    "SpecRich4Shape":"float",
    "SpecRich4Dim1":"float",
    "SpecRich4Dim2":"float",
    "SpecRich4Area":"float",
    "SpecRich5Container":"float",
    "SpecRich5Shape":"float",
    "SpecRich5Dim1":"float",
    "SpecRich5Dim2":"float",
    "SpecRich5Area":"float",
    "SpecRich6Container":"float",
    "SpecRich6Shape":"float",
    "SpecRich6Dim1":"float",
    "SpecRich6Dim2":"float",
    "SpecRich6Area":"float",
    "Notes" : "text",
    "DateLoadedInDb" : "date",
    "PrimaryKey" : "v_100",
    "DBKey" : "text",



    "Species" : "text",
    "ProjectKey" : "text",

    "DENSITY" : "float",

}
